on:
  push:
    branches:
      - main
  workflow_dispatch:

name: 🚀 Deploy to Production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '14.x'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build Project
      env:
        CI: false
        GENERATE_SOURCEMAP: false

      run: yarn build

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.PRODUCTION_FTP_HOST }}
        username: ${{ secrets.PRODUCTION_FTP_USER }}
        password: ${{ secrets.PRODUCTION_FTP_PASSWORD }}
        local-dir: build/
        server-dir: /
